server:
  port: 8087

spring:
 cloud:
   gateway:
     server:
       webflux:
         routes:
          - id: student-service
            uri: lb://STUDENT-SERVICE
            predicates:
              - Path=/students/**
          - id: formation-service
            uri: lb://FORMATION-SERVICE
            predicates:
              - Path=/formations/**
          - id: module-service
            uri: lb://MODULE-SERVICE
            predicates:
              - Path=/modules/**
          - id: inscription-service
            uri: lb://INSCRIPTION-SERVICE
            predicates:
              - Path=/inscriptions/**
         discovery:
          locator:
           enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true   #le service s’enregistre automatiquement
    fetch-registry: true   #le service peut voir les autres services sur Eureka