server:
  port: 8087

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/students/**
        - id: formation-service
          uri: lb://FORMATION-SERVICE
          predicates:
            - Path=/formations/**
        - id: module-service
          uri: lb://MODULE-SERVICE
          predicates:
            - Path=/modules/**
        - id: inscription-service
          uri: lb://INSCRIPTION-SERVICE
          predicates:
            - Path=/inscriptions/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true   #le service s’enregistre automatiquement
    fetch-registry: true   #le service peut voir les autres services sur Eureka